name: Test and Manage Issues

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write
  checks: write

jobs:
  test-and-manage-issues:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4

      -
        name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      -
        name: Install dependencies
        run: npm ci

      -
        name: Get version from package.json
        id: get_version
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      -
        name: Run tests
        id: test
        run: npm test -- --ci

      -
        name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        if: failure() || success()
        with:
          check_name: "Test Results (${{ github.event.workflow_run.event || github.event_name }})"
          files: "test-results/**/*.xml"
          comment_mode: "off"

      -
        name: Check URL
        if: failure() || success()
        run: |
          echo "CHECK_URL=${{ fromJSON( steps.test-results.outputs.json ).check_url }}" >> $GITHUB_ENV

      -
        name: Create or update issue if tests fail
        if: ${{ failure() &&  steps.test.conclusion != 'success' }}
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const version = process.env.PACKAGE_VERSION;
            const checkUrl = process.env.CHECK_URL;
            const issueTitle = `Test Failure for version ${version}`;
            const issueBody = `
              The tests failed for the latest commit under version ${version}.

              **Workflow:** ${context.workflow}
              **Job:** ${context.job}
              **Run:** ${context.runId}
              **Commit:** ${context.sha}

              Please check the [Test results](${checkUrl}) for more details.
            `;

            const existingIssues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'open',
              labels: 'test-failure'
            });

            const issueExists = existingIssues.data.find(issue => issue.title === issueTitle);

            if (issueExists) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issueExists.number,
                body: `New test failure detected for version ${version}. Please check the latest [Test results](${checkUrl}) for more details.`
              });
            } else {
              await github.rest.issues.create({
                owner,
                repo,
                title: issueTitle,
                body: issueBody,
                labels: ['test-failure']
              });
            }

      -
        name: Close issue if tests pass
        if: ${{ steps.test.conclusion == 'success' }}
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const version = process.env.PACKAGE_VERSION;
            const issueTitle = `Test Failure for version ${version}`;

            const existingIssues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'open',
              labels: 'test-failure'
            });

            const issueExists = existingIssues.data.find(issue => issue.title === issueTitle);

            if (issueExists) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issueExists.number,
                body: `New test for version ${version} passed without error. Going to close the issue.`
              });
              await github.rest.issues.update({
                owner,
                repo,
                issue_number: issueExists.number,
                state: 'closed'
              });
            }